In [185]:
import numpy as np
gX = 3
gY = 3

In [186]:
shape1 =  []
for i in range(gX*gY):
    a = np.zeros(gX*gY)
    a[i] = 1
    shape1.append(a.reshape((gX,gY))) 

    
shape2 = []
for i in range(gX*gY):
    if (i+1)%gX != 0:
        a = np.zeros(gX*gY)
        a[i]=1
        a[i+1] =1
        shape2.append(a.reshape((gX,gY))) 
        
shape3 = []
for i in range(gX*gY):
    if ((i+1)%gX != 0) & ((i+1)%gX != gX - 1):
        a = np.zeros(gX*gY)
        a[i]=1
        a[i+1] =1
        a[i+2] = 1
        shape3.append(a.reshape((gX,gY))) 
    
shape4 = []
for j in range(gX - 2):
    for i in range(gY - 1):
        a = np.zeros(gX*gY).reshape((gX,gY))
        for k in range(3):
            a[i][j+k] = 1
            a[i+1][j+k] = 1
        shape4.append(a)
        
shape5 = []
for j in range(gX - 2):
    for i in range(gY - 1):
        a = np.zeros(gX*gY).reshape((gX,gY))
        a[i][j] = 1
        a[i][j+1] = 1
        a[i+1][j+1] = 1
        a[i+1][j+2] = 1
        shape5.append(a)      
        
shape6 = []
for j in range(gX - 2):
    for i in range(gY - 1):
        a = np.zeros(gX*gY).reshape((gX,gY))
        a[i][j+1] = 1
        a[i][j+2] = 1
        a[i+1][j] = 1
        a[i+1][j+1] = 1
        shape6.append(a)   
    
shape7 = []
for j in range(gX - 2):
    for i in range(gY - 1):
        a = np.zeros(gX*gY).reshape((gX,gY))
        a[i][j+1] = 1
        a[i+1][j] = 1
        a[i+1][j+1] = 1
        a[i+1][j+2] = 1
        shape7.append(a)    
          
shape8 = []
for j in range(gX - 2):
    for i in range(gY - 1):
        a = np.zeros(gX*gY).reshape((gX,gY))
        a[i][j+1] = 1
        a[i][j+2] = 1
        a[i+1][j] = 1
        a[i+1][j+1] = 1
        a[i+1][j+2] = 1
        shape8.append(a)
    
shape9 = []
for j in range(gX - 2):
    for i in range(gY - 1):
        a = np.zeros(gX*gY).reshape((gX,gY))
        a[i][j] = 1
        a[i][j+1] = 1
        a[i+1][j] = 1
        a[i+1][j+1] = 1
        a[i+1][j+2] = 1
        shape9.append(a)

    
shape41 = []
for j in range(gX - 1):
    for i in range(gY - 1):
        a = np.zeros(gX*gY).reshape((gX,gY))
        a[i][j] = 1
        a[i][j+1] = 1
        a[i+1][j] = 1
        shape41.append(a)


In [187]:
# 1   11(2)  111(2)  111(2)     110(2)      011(2)      010(4)     011(4)    110(4)  110(4)
#                    111        011         110         111        111       111     100 
# 1   2      3       4          5           6           7          8         9       41



In [188]:
shape41

[array([[ 1.,  1.,  0.],
        [ 1.,  0.,  0.],
        [ 0.,  0.,  0.]]), array([[ 0.,  0.,  0.],
        [ 1.,  1.,  0.],
        [ 1.,  0.,  0.]]), array([[ 0.,  1.,  1.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  0.]]), array([[ 0.,  0.,  0.],
        [ 0.,  1.,  1.],
        [ 0.,  1.,  0.]])]

In [189]:
#shape10 is empty
#shape11 is shape1

In [190]:
shape12 = []
for x in shape2:
    shape12.append(np.array(zip(*x[::-1])))
shape13 = []
for x in shape3:
    shape13.append(np.array(zip(*x[::-1])))
shape14 = []
for x in shape4:
    shape14.append(np.array(zip(*x[::-1])))
shape15 = []
for x in shape5:
    shape15.append(np.array(zip(*x[::-1])))
shape16 = []
for x in shape6:
    shape16.append(np.array(zip(*x[::-1])))
    
shape17 = []
for x in shape7:
    shape17.append(np.array(zip(*x[::-1])))
shape27 = []
for x in shape17:
    shape27.append(np.array(zip(*x[::-1])))
shape37 = []
for x in shape27:
    shape37.append(np.array(zip(*x[::-1])))
    
shape18 = []
for x in shape8:
    shape18.append(np.array(zip(*x[::-1])))
shape28 = []
for x in shape18:
    shape28.append(np.array(zip(*x[::-1])))
shape38 = []
for x in shape28:
    shape38.append(np.array(zip(*x[::-1])))
    
shape19 = []
for x in shape9:
    shape19.append(np.array(zip(*x[::-1])))
shape29 = []
for x in shape19:
    shape29.append(np.array(zip(*x[::-1])))
shape39 = []
for x in shape29:
    shape39.append(np.array(zip(*x[::-1])))

shape51 = []
for x in shape41:
    shape51.append(np.array(zip(*x[::-1])))
shape61 = []
for x in shape51:
    shape61.append(np.array(zip(*x[::-1])))
shape71 = []
for x in shape61:
    shape71.append(np.array(zip(*x[::-1])))

In [191]:
dict={}
dict[1] = shape1
dict[2] = shape2
dict[3] = shape3
dict[4] = shape4
dict[5] = shape5
dict[6] = shape6
dict[7] = shape7
dict[8] = shape8
dict[9] = shape9
dict[12] = shape12
dict[13] = shape13
dict[14] = shape14
dict[15] = shape15
dict[16] = shape16
dict[17] = shape17
dict[18] = shape18
dict[19] = shape19
dict[27] = shape27
dict[28] = shape28
dict[29] = shape29
dict[37] = shape37
dict[38] = shape38
dict[39] = shape39
dict[41] = shape41
dict[51] = shape51
dict[61] = shape61
dict[71] = shape71

In [192]:
#try to solve
def solve(matrix, array, b, l):
    global hh
    k =array
    h = b+1
    listt = l
    if len(k) !=0:
        a = k[0]
        for j in range(len(dict[a])):
            listt[h] = j
            #print (listt)
           
            if ((((matrix + dict[a][j])%2).reshape(1,9) == np.ones(9)).all()) & (len(listt)-1 == h):
                hh = hh +1 
                print "done"
                print listt
                return listt
                
            
            elif hh == 0:
                solve(matrix + dict[a][j], k[1:], h , listt )
                return listt
            
    


In [193]:
def summary(matrix, array):
    global hh
    hh = 0 
    b = -1
    l = -1*np.ones(len(array))
    solution = solve(matrix, array, b, l)
    if solution is None:
        print 'fail'
    else:
        solution = solution.astype(int)
        print "%%%%%%%%%%"
        print "operations: "
        for i in range(len(array)):
            print dict[array[i]][solution[i]] 
        print "%%%%%%%%%%"    
        print "step to result: "
        print matrix%2
        for i in range(len(array)):
            matrix = matrix + dict[array[i]][solution[i]]
            print matrix%2
 
    

In [194]:
# 1   11(2)  111(2)  111(2)     110(2)      011(2)      010(4)     011(4)    110(4)  110(4)
#                    111        011         110         111        111       111     100 
# 1   2      3       4          5           6           7          8         9       41


In [195]:
#input initial
matrix = np.array([0,1,0,0,0,1,0,0,1]).reshape((3,3))
array = [61,61,3,12,12,12,37,3,41,17,41]

In [196]:
for x in array:
    print dict[x][0]

[[ 0.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  1.]]
[[ 0.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  1.]]
[[ 1.  1.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]
[[ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]
[[ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]
[[ 0.  1.  0.]
 [ 1.  1.  0.]
 [ 0.  1.  0.]]
[[ 1.  1.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]]
[[ 0.  1.  0.]
 [ 0.  1.  1.]
 [ 0.  1.  0.]]
[[ 1.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]]


In [197]:
summary(matrix,array)


%%%%%%%%%%
operations: 
[[ 0.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  1.]]
[[ 0.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  1.]]
[[ 1.  1.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]
[[ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]
[[ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]
[[ 0.  1.  0.]
 [ 1.  1.  0.]
 [ 0.  1.  0.]]
[[ 1.  1.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]]
[[ 0.  1.  0.]
 [ 0.  1.  1.]
 [ 0.  1.  0.]]
[[ 1.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]]
%%%%%%%%%%
step to result: 
[[0 1 0]
 [0 0 1]
 [0 0 1]]
[[ 0.  1.  0.]
 [ 0.  0.  0.]
 [ 0.  1.  0.]]
[[ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]]
[[ 1.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  1.]]
[[ 1.  1.  0.]
 [ 1.  1.  0.]
 [ 0.  1.  1.]]
[[ 0.  0.  1.]
 [ 1.  1.  0.]
 [ 0.  1.  1.]]
[[ 1.  1.  1.]
 [ 0.  1.  0.]
 [ 0.  1.  1.]]
